import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import { Providers } from "@/components/providers/providers";
import "@rainbow-me/rainbowkit/styles.css";
import { Navbar } from "@/components/navbar";
import { ErrorBoundary } from "@/components/error-boundary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-surface-primary text-text-primary min-h-screen`}
      >
        <div>
          <Providers>
            <Navbar />
            <ErrorBoundary>
              <main>{children}</main>
            </ErrorBoundary>
          </Providers>
        </div>
      </body>
    </html>
  );
}
